---
- import_tasks: setup-RedHat.yml
  when:
    - ansible_os_family in ["RedHat", "Rocky", "OracleLinux"]
    - ansible_distribution_major_version == "8"

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
