---
- name: DEBIAN | Install requirements
  ansible.builtin.package:
    name: "{{ locales_dependencies }}"
    state: present

- name: UBUNTU | Install language packs
  ansible.builtin.package:
    name: "{{ locales_language_packs_present }}"
    state: present
  when: ansible_distribution == 'Ubuntu'
  notify: update locales

- name: UBUNTU | Remove language packs
  ansible.builtin.package:
    name: "{{ locales_language_packs_absent }}"
    state: absent
  when: ansible_distribution == 'Ubuntu'
  notify: update locales

- name: DEBIAN | Detect locale gen file
  ansible.builtin.stat:
    path: "{{ locales_gen_file }}"
  register: locales_gen_file

- name: DEBIAN | Create locale gen file if not exist
  ansible.builtin.file:
    path: "{{ locales_gen_file }}"
    mode: 0644
    state: touch
  when: not locales_gen_file.stat.exists

- name: DEBIAN | Ensure locales are present
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales_present }}"

- name: DEBIAN | Ensure locales are absent
  community.general.locale_gen:
    name: "{{ item }}"
    state: absent
  with_items: "{{ locales_absent }}"

- name: DEBIAN | Set default locale
  ansible.builtin.template:
    src: locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
