---
- name: REDHAT | Install languages pack
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales_language_packs_present }}"

- name: REDHAT | Set default locale
  ansible.builtin.command: "localectl set-locale LANG={{ locales_default.lang }}"
  changed_when: false
